### ISSUE TITLE
Problem when i show a second time

### ISSUE THREAD

**Issue by siddhinho** [tichise/FormSheetTextView#4]
When i show for a second time the app crash 

This is the error 
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

On FormSheetTextViewController
On function
@objc func keyboardWillChangeFrame(notification: NSNotification) {

on line 146

bottomConstraint.constant = keyboardHeight - ((windowHeight - formSheetHeight - statusBarHeight)) + 10

**Comment by tichise** [comment]
@siddhinho It has been fixed in 1.4.0. Thank you for the report.
https://github.com/tichise/FormSheetTextView/releases/tag/1.4.0
